# Generated by Django 4.2.16 on 2025-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="github_url",
            field=models.URLField(
                blank=True,
                help_text="Optional. Example: https://github.com/username/repo",
                max_length=500,
                null=True,
                verbose_name="GitHub repository URL",
            ),
        ),
    ]
